version: '3'

volumes:
  db:
  logs:
  bot:

services:

  db:
    image: postgres:12
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  bot:
    build: .
    depends_on:
      - db
    command: python -m bot
