"""Add balance

Revision ID: 24588099b7d7
Revises: cfec3b3ceffc
Create Date: 2022-07-18 22:32:41.990174

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '24588099b7d7'
down_revision = 'cfec3b3ceffc'
branch_labels = None
depends_on = None

create_add_balance_trigger_func = sa.text("""
create or replace
function add_balance_trigger() returns trigger as $body$
begin 
	update
	public.users
set
	balance = balance + new.amount
where
	id = new.user_id;
return null;
end;
$body$ language plpgsql;
""")
drop_add_balance_trigger_func = sa.text("""drop function if exists add_balance_trigger;""")
create_add_balance_trigger = sa.text("""
create trigger add_balance after
insert
    on
	public.expenses for each row execute procedure add_balance_trigger()
""")
drop_add_balance_trigger = sa.text("""drop trigger if exists add_balance on public.expenses;""")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expense_comment', table_name='expenses')
    op.create_index(op.f('ix_expenses_comment'), 'expenses', ['comment'], unique=False)
    op.add_column('users', sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False,
                                     server_default=sa.text("0.00::numeric")))
    op.execute(drop_add_balance_trigger)
    op.execute(create_add_balance_trigger_func)
    op.execute(create_add_balance_trigger)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(drop_add_balance_trigger)
    op.execute(drop_add_balance_trigger_func)
    op.drop_column('users', 'balance')
    op.drop_index(op.f('ix_expenses_comment'), table_name='expenses')
    op.create_index('ix_expense_comment', 'expenses', ['comment'], unique=False)
    # ### end Alembic commands ###
